---
version: "2"
services:
  drug-div-db:
    image: "docker.iatric.com/drug-div-db:8.0-debian"
    command:
      - "/mnt/entrypoint.sh"
    environment:
      - "TZ=UTC"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DOCKER_HOSTNAME=localhost"
      - "DOCKER_HOSTIPADDR=127.0.0.1"
      - "CLIENT_CODE=vah"
      - "CLIENT_TEXT_DESCRIPTION=Site Name"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "TERM=xterm"
      - "GOSU_VERSION=1.12"
      - "MYSQL_DATABASE=drug-div-db"
      - "PRODUCTION=true"
    volumes:
      - "drug-div-db:/var/lib/mysql"
    hostname: "drug_div_db"
    ports:
      - "3316:3306"
    logging:
      driver: "json-file"
    restart: "always"
    networks:
      - "iatric"
  solomon-db:
    image: "docker.iatric.com/solomon-db:2.1.4"
    mem_limit: 17179869184
    command:
      - "/mnt/entrypoint.sh"
    environment:
      - "TZ=UTC"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DOCKER_HOSTNAME=localhost"
      - "DOCKER_HOSTIPADDR=127.0.0.1"
      - "CLIENT_CODE=vah"
      - "CLIENT_TEXT_DESCRIPTION=Site Name"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "TERM=xterm"
      - "GOSU_VERSION=1.12"
      - "MYSQL_DATABASE=solomon"
      - "CONTAINER_NAME=Solomon Database"
      - "PRODUCTION=true"
    volumes:
      - "db-backup-solomon-local:/mnt/backup"
      - "all-logs-local:/mnt/log"
      - "config-ini-solomon-local:/mnt/config"
      - "solomon-db-files-local:/var/lib/mysql"
    working_dir: "/solomon/data"
    hostname: "solomon-db"
    ports:
      - "3335:3306"
    logging:
      driver: "json-file"
    restart: "always"
    networks:
      - "iatric"
  solomon-drug-div:
    image: "docker.iatric.com/solomon-drug-div:1.0"
    mem_limit: 17179869184
    environment:
      - "TZ=UTC"
      - "DRUG_DIV_DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DRUG_DIV_DB_SERVER=drug_div_db"
      - "DRUG_DIV_DATABASE=drug-div-db"
      - "DRUG_DIV_DB_USER=root"
      - "DRUG_DIV_RUN_LOAD=True"
      - "DRUG_DIV_LOAD_IMPORT_PATH=/mnt/dataloadfiles/"
      - "DRUG_DIV_LOAD_LOG_PATH=/mnt/log/drug_div_proc/data_load/"
      - "DRUG_DIV_ML_TRAINING=False"
      - "CLIENT_CODE=vchqcr"
      - "CLIENT_TEXT_DESCRIPTION=VCH QCR TEST"
      - "DATA_FEED=meditech"
      - "PRODUCT_PLATFORM=drug_div"
      - "_JAVA_OPTIONS=-Xmx49152M"
      - "FASTLANE_BASE_URL=https://${SERVER_HOSTNAME}:44400"
      - "FASTLANE_USERNAME=ava.user"
      - "FASTLANE_PASSWORD=${MYSQL_PASSWORD}"
      - "APPLICATION_API=https://${SERVER_HOSTNAME}:44400"
      - "APPLICATIONMANAGER_API=https://${SERVER_HOSTNAME}:44400"
      - "DOCKER_HOSTNAME=localhost"
      - "DOCKER_HOSTIPADDR=127.0.0.1"
      - "SOLOMON_DB_USERNAME=root"
      - "SOLOMON_DB_PASSWORD=${MYSQL_PASSWORD}"
      - "SOLOMON_DB_NAME=solomon"
      - "SOLOMON_DB_HOSTNAME=solomon-db"
      - "SOLOMON_DB_DIALECT=mysql"
      - "SPARK_LOCAL_HOSTNAME=localhost"
      - "DRUG_DIV_DB_HOSTNAME=drug_div_db"
      - "PATH=/usr/lib/spark-3.0.1-bin-hadoop2.7/bin/:/usr/lib/spark-3.0.1-bin-hadoop2.7/bin/:/usr/lib/spark-3.0.1-bin-hadoop2.7/sbin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "TERM=xterm"
      - "SPARK_VERSION=3.0.1"
      - "HADOOP_VERSION=2.7"
      - "SPARK_HOME=/usr/lib/spark-3.0.1-bin-hadoop2.7"
      - "PYTHONPATH=/usr/lib/spark-3.0.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip:/usr/lib/spark-3.0.1-bin-hadoop2.7/python:/usr/lib/spark-3.0.1-bin-hadoop2.7/python/build:"
      - "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64"
      - "PRODUCTION="
      - "SFTP_PASSWORD=${MYSQL_PASSWORD}"
      - "DRUG_DIV_DB_PORT=3306"
      - "SCRIPT_INSIDE_DOCKER=true"
    privileged: true
    depends_on:
      - "solomon-db"
    volumes:
      - "all-logs-local:/mnt/log"
      - "solomon-data-volume-local:/mnt/solomon_data"
      - "dataloadfiles-local:/mnt/dataloadfiles"
      - "config-ini-volume-local:/mnt/config"
      - "./config:/mnt/src/solomon/core/solomon/de_config/configurations"
    working_dir: "/mnt/src/drug_div"
    hostname: "solomon-drug-div"
    ports:
      - "18081:18080"
      - "3500:3501"
      - "4041:4040"
      - "9801:9800"
    logging:
      driver: "json-file"
    restart: "always"
    networks:
      - "iatric"
  sftp-host:
    image: "docker.iatric.com/solomon-sftp:1.0"
    command:
      - "/entrypoint"
      - "drug_div_test:${MYSQL_PASSWORD}:1001"
    environment:
      - "TZ=UTC"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "TERM=xterm"
    volumes:
      - "sftp-files-local:/iat/upload"
    hostname: "sftp-host"
    ports:
      - "2222:22"
    logging:
      driver: "json-file"
    restart: "always"
    networks:
      - "iatric"
  nginx:
    image: "docker.iatric.com/solomon-nginx:1.0"
    hostname: "secure_metabase"
    ports:
      - "3443:443"
    restart: "always"
    depends_on:
      - "metabase"
      - "ava"
      - "fastlane"
    environment:
      - "NGINX_HOST=${SERVER_HOSTNAME}"
      - "NGINX_INSTANCE=DEV"
    command: /bin/sh -c "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - "iatric"
  metabase:
    image: "registry.hub.docker.com/metabase/metabase:v0.41.7"
    environment:
      - "MD_DB_FILE=/home/metabase/metabase.db"
    ports:
      - "3000:3000"
    volumes:
      - "metabase-files-local:/metabase.db"
    hostname: "metabase"
    restart: "always"
    networks:
      - "iatric"
  drugdiversion:
    image: "docker.iatric.com/detectrx:1.0-alpine"
    dns:
      - 192.168.0.9
    mem_limit: 17179869184
    ports:
      - "3001:3001"
    environment:
      - "NODE_ENV=development"
      - "NODE_TLS_REJECT_UNAUTHORIZED=0"
      - "APPLICATION_UUID=e65fa53d-c954-43f5-8c2c-a08456f11829"
      - "APPLICATION_API=https://${SERVER_HOSTNAME}:3001/api"
      - "APPLICATION_NAME=DRUGDIVERSION"
      - "APPLICATION_URL=https://${SERVER_HOSTNAME}:3001/"
      - "APPLICATIONMANAGER_API=https://fastlane/api"
      - "APPLICATIONMANAGER_API_CLIENT=https://${SERVER_HOSTNAME}:44400/api"
      - "DB_DIALECT=mysql"
      - "DB_HOSTNAME=drug_div_db"
      - "DB_LOGGING=0"
      - "DB_NAME=drug-div-db"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_PORT=3306"
      - "DB_USERNAME=root"
      - "X_AUTH_TOKEN_SECRET=jwtSecret"
      - "X_AUTH_TOKEN_EXPIRATION=15"
      - "X_AUTH_REFRESH_TOKEN_SECRET=jwtSecret"
      - "X_AUTH_RERESH_TOKEN_EXPIRATION=480"
    restart: "always"
    volumes:
      - "dataloadfiles-local:/mnt/dataloadfiles" # We want to be able to look at the solomon-drug-div import errors and ddhold files
    depends_on:
      - "drug-div-db"
      - "fastlane"
    networks:
      - "iatric"
  ava:
    image: "docker.iatric.com/solomon-ava-client:1.0-alpine"
    mem_limit: 17179869184
    ports:
      - "3002:3001"
    depends_on:
      - "solomon-db"
      - "drug-div-db"
    environment:
      - "NODE_ENV=development"
      - "NODE_TLS_REJECT_UNAUTHORIZED=0"
      - "APPLICATION_UUID=0a3625f8-ae53-4428-866a-928e29bf6327"
      - "APPLICATION_API=https://${SERVER_HOSTNAME}:3002/api"
      - "APPLICATION_NAME=AVA"
      - "APPLICATION_URL=https://${SERVER_HOSTNAME}:3002/"
      - "APPLICATIONMANAGER_API=https://fastlane/api"
      - "APPLICATIONMANAGER_API_CLIENT=https://${SERVER_HOSTNAME}:44400/api"
      - "X_AUTH_TOKEN_SECRET=jwtSecret"
      - "X_AUTH_TOKEN_EXPIRATION=15"
      - "X_AUTH_REFRESH_TOKEN_SECRET=jwtSecret"
      - "X_AUTH_RERESH_TOKEN_EXPIRATION=480"
      - "SOLOMON_DB_DIALECT=mysql"
      - "SOLOMON_DB_HOSTNAME=solomon-db"
      - "SOLOMON_DB_LOGGING=false"
      - "SOLOMON_DB_NAME=solomon"
      - "SOLOMON_DB_PASSWORD=${MYSQL_PASSWORD}"
      - "SOLOMON_DB_PORT=3306"
      - "SOLOMON_DB_USERNAME=root"
      - "PRODUCT_DB_DIALECT=mysql"
      - "PRODUCT_DB_HOSTNAME=drug_div_db"
      - "PRODUCT_DB_LOGGING=false"
      - "PRODUCT_DB_NAME=drug_div"
      - "PRODUCT_DB_PASSWORD=${MYSQL_PASSWORD}"
      - "PRODUCT_DB_PORT=3306"
      - "PRODUCT_DB_USERNAME=root"
      - "PRODUCT_PLATFORM=drug_div"
    restart: "always"
    hostname: "ava"
    networks:
      - "iatric"
    volumes:
      - "/home/iatric/certificates:/app/certificates"
  fastlane:
    image: "docker.iatric.com/fastlane:latest-alpine"
    ports:
      - "44400:443"
    depends_on:
      - "fastlane-db"
    environment:
      - "APPLICATION_UUID=ef38f527-7e47-a978-cd4c51789a52"
      - "APPLICATION_NAME=Fastlane"
      - "APPLICATION_API=https://fastlane/api"
      - "APPLICATION_API_CLIENT=https://${SERVER_HOSTNAME}:44400/api"
      - "APPLICATIONMANAGER_API=https://fastlane/api"
      - "APPLICATIONMANAGER_API_CLIENT=https://${SERVER_HOSTNAME}:44400/api"
      - "APPLICATION_URL=https://${SERVER_HOSTNAME}:44400/"
      - "APPLICATION_VERSION=1.3.0"
      - "APPLICATION_COPYRIGHT=2022"
      - "NODE_ENV=development"
      - "PORT=44400"
      - "NODE_TLS_REJECT_UNAUTHORIZED=0"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_NAME=fastlane"
      - "DB_HOSTNAME=fastlane-db"
      - "DB_PORT=3306"
      - "DB_DIALECT=mysql"
      - "DB_LOGGING=false"
      - "X_AUTH_TOKEN_SECRET=jwtSecret"
      - "X_AUTH_TOKEN_EXPIRATION=15"
      - "X_AUTH_REFRESH_TOKEN_SECRET=jwtSecret"
      - "X_AUTH_REFRESH_TOKEN_EXPIRATION=480"
      - "ICONNECT_SITECODE=IAT"
    restart: "always"
    hostname: "fastlane"
    volumes:
      - "/home/iatric/certificates:/app/certificates"
    networks:
      - "iatric"
  fastlane-db:
    image: "docker.iatric.com/solomon-fastlane-db:5.7-debian"
    environment:
      - "TZ=UTC"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_TCP_PORT=3306"
    volumes:
      - "fastlane-db:/var/lib/mysql"
    hostname: "fastlane-db"
    ports:
      - "3326:3306"
    logging:
      driver: "json-file"
    restart: "always"
    networks:
      - "iatric"

networks:
  iatric:
    external: true
volumes:
  all-logs-local:
    external: false
  solomon-config-volume-local:
    external: false
  solomon-data-volume-local:
    external: false
  config-ini-volume-local:
    external: false
  dataloadfiles-local:
    external: false
  config-ini-solomon-local:
    external: false
  solomon-db-files-local:
    external: false
  db-backup-solomon-local:
    external: false
  sftp-files-local:
    external: false
  metabase-files-local:
    external: false
  drug-div-db:
    external: false
  fastlane-db:
    external: false
