version: '3.7'

services:

  app:
    container_name: lms_${ENVIRONMENT}
    hostname: lms_${ENVIRONMENT}
    networks:
      - iatric
    image: docker.iatric.com/sedona_lms:${VERSION}-alpine
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${APP_PORT}:443/tcp
    volumes:
      - /home/iatric/certificates:/app/certificates
    environment:
      APPLICATION_API: https://lms_${ENVIRONMENT}/api
      APPLICATION_API_CLIENT: https://${SERVER_HOSTNAME}:${APP_PORT}/api
      APPLICATION_NAME: Sedona LMS [${ENVIRONMENT}]
      APPLICATION_URL: https://${SERVER_HOSTNAME}:${APP_PORT}/
      APPLICATION_UUID: ea7a8969-e3b3-4726-9912-67c8f8270d44
      APPLICATIONMANAGER_API: https://fastlane_${ENVIRONMENT}/api
      APPLICATIONMANAGER_API_CLIENT: https://${SERVER_HOSTNAME}:${FASTLANE_PORT}/api
      DB_DIALECT: mysql
      DB_HOSTNAME: ${MYSQL_HOST}
      DB_LOGGING: 0
      DB_NAME: lms_${ENVIRONMENT}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      ICONNECT_SITECODE: ${SITE_CODE}
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 443
      X_AUTH_REFRESH_TOKEN_EXPIRATION: 480
      X_AUTH_REFRESH_TOKEN_SECRET: ${TOKEN_SECRET}
      X_AUTH_TOKEN_EXPIRATION: 15
      X_AUTH_TOKEN_SECRET: ${TOKEN_SECRET}

networks:
  iatric:
    external: true
